inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 135
  Exclude:
    - lib/etd_transformer/senior_theses_transformer.rb
    - spec/etd_transformer/senior_thesis_transformer_spec.rb
    - spec/etd_transformer/vireo/submission_spec.rb
    - spec/etd_transformer/vireo/export_spec.rb

Metrics/AbcSize:
  Exclude:
    - lib/etd_transformer/dataspace/submission.rb
    - lib/etd_transformer/cli.rb

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - lib/etd_transformer/dataspace/submission.rb
    - lib/etd_transformer/senior_theses_transformer.rb

Style/GlobalVars:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false
