inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 135
  Exclude:
    - lib/etd_transformer/transformer.rb

Metrics/AbcSize:
  Exclude:
    - lib/etd_transformer/dataspace/submission.rb

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - lib/etd_transformer/dataspace/submission.rb

Style/GlobalVars:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false
