inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 135
  Exclude:
    - lib/etd_transformer/transformer.rb
    - spec/etd_transformer/transformer_spec.rb
    - spec/etd_transformer/vireo/submission_spec.rb

Metrics/AbcSize:
  Exclude:
    - lib/etd_transformer/dataspace/submission.rb

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - lib/etd_transformer/dataspace/submission.rb

Style/GlobalVars:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false
